version: 2

jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: setup a venv
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            make install-dev
      - save_cache:
          name: Save python deps cache
          key: deps-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
          - ~/venv
      - run:
          name: Run tests
          command: . ~/venv/bin/activate; make test-all
  publish:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" > ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          name: init .pypirc
          command: . ~/venv/bin/activate; make publish
workflows:
  version: 2
  test-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
